Hi Thomas,
Thanks for the feedback, although a number of issues remain.
Same thing; I have the feeling in the failed test there is being checked for identity ( id(aObject) rather than equality ( aObject == anotherObject ).
Hashing test for identity, not equality.

This is something we need to look into, since it is important to be able to compare TopoDS_* types.




jelle_laptop:unittest localadmin$ py hashing_unittest.py
FF
======================================================================
FAIL: testGP (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "hashing_unittest.py", line 28, in testGP
    self.assertEqual(p1,p3)
AssertionError: <OCC.gp.gp_Pnt; proxy of <Swig Object of type 'gp_Pnt *' at 0x105cb8950> > != <OCC.gp.gp_Pnt; proxy of <Swig Object of type 'gp_Pnt *' at 0x105cb8990> >

======================================================================
FAIL: testTopoDS (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "hashing_unittest.py", line 41, in testTopoDS
    self.assertEqual(box1,box2)
AssertionError: <OCC.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x100c6be18> > != <OCC.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x100c68018> >

----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (failures=2)
jelle_laptop:unittest localadmin$